---
abstract: 'source constants from POD to avoid repetition'
author:
  - 'Richard Harris <RJH@cpan.org>'
build_requires:
  Test::Exception: 0
  Test::More: 0
  Test::Warn: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Constant
requires:
  Carp: 0
  Pod::Parser: 0
  Scalar::Util: 0
  Text::Balanced: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/richardjharris/Pod-Constant/issues
  repository: git://github.com/richardjharris/Pod-Constant.git
version: 0.1
